version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu_projeto_app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///rastreamento_entregas.db
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    ports:
      - "5000:5000"
    command: python app.py

  db:
    image: mysql:8.0
    container_name: meu_projeto_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: meu_projeto
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
